name: Docker Image CI

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [main]

permissions: write-all

jobs:
  build_and_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.Beastspy }}

      - name: Build Docker image
        id: build_image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}
          IMAGE_TAG=${{ github.sha }}
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          echo "Building Docker image with tag: $IMAGE_TAG"
          docker image build -t $IMAGE_ID:$IMAGE_TAG .
          IMAGE_SHA=$(docker inspect --format='{{index .Id}}' $IMAGE_ID:$IMAGE_TAG)
          echo "::set-output name=image_sha::$IMAGE_SHA"

      - name: Install Trivy
        run: |
          sudo apt-get update -y
          sudo apt-get install wget -y
          wget https://github.com/aquasecurity/trivy/releases/download/v0.30.0/trivy_0.30.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.30.0_Linux-64bit.deb
 
      - name: Scan Docker image for vulnerabilities
        run: |
          IMAGE_SHA=${{ steps.build_image.outputs.image_sha }}
          echo "Scanning Docker image with SHA: $IMAGE_SHA"
          trivy image --severity HIGH,CRITICAL $IMAGE_SHA --format sarif --output trivy-report.sarif

      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: trivy-report.sarif
          
     
      - name: Push Docker image if scan is successful
        if: success()
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}
          IMAGE_TAG=${{ github.sha }}
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          echo "Pushing Docker image with tag: $IMAGE_TAG"
          docker image push $IMAGE_ID:$IMAGE_TAG
