name: Docker Image CI

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write
  actions: read
  security-events: write

jobs:
  build_and_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.BEASTSPY }}

      - name: Build Docker image
        id: build_image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}
          IMAGE_TAG=${{ github.sha }}
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          echo "Building Docker image with tag: $IMAGE_TAG"
          docker build -t $IMAGE_ID:$IMAGE_TAG .
          IMAGE_SHA=$(docker inspect --format='{{index .Id}}' $IMAGE_ID:$IMAGE_TAG)
          echo "image_sha=$IMAGE_SHA" >> $GITHUB_ENV
          echo "IMAGE_ID=$IMAGE_ID" >> $GITHUB_ENV
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "IMAGE_SHA=$IMAGE_SHA" >> $GITHUB_ENV

      - name: Install Trivy
        run: |
          sudo apt-get update -y
          sudo apt-get install wget -y
          wget https://github.com/aquasecurity/trivy/releases/download/v0.30.0/trivy_0.30.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.30.0_Linux-64bit.deb

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Display funding options
        run: npm fund

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Run Snyk to check for vulnerabilities
        run: |
          snyk container test $IMAGE_ID:$IMAGE_TAG --severity-threshold=high --sarif > snyk-container-report.sarif || (cat snyk-container-report.sarif && echo "Snyk test failed with exit code $?")
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Validate Snyk SARIF report
        run: |
          jq . snyk-container-report.sarif || echo "Invalid Snyk SARIF report"

      - name: Upload Snyk SARIF report
        uses: actions/upload-artifact@v3
        with:
          name: snyk-container-report
          path: snyk-container-report.sarif

      - name: Upload Snyk SARIF report to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-container-report.sarif

      - name: Scan Docker image for vulnerabilities with Trivy
        run: |
          IMAGE_SHA=${{ env.IMAGE_SHA }}
          echo "Scanning Docker image with SHA: $IMAGE_SHA"
          trivy image --severity HIGH,CRITICAL $IMAGE_SHA --format sarif --output trivy-report.sarif

      - name: Upload Trivy SARIF report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-report.sarif

      - name: Set up ShiftLeft CLI
        run: |
          # Download and install ShiftLeft CLI
          curl -L -o /usr/local/bin/sl https://cdn.shiftleft.io/download/sl
          chmod a+rx /usr/local/bin/sl

      - name: Run ShiftLeft scan
        run: |
          sl-latest scan \
            --org ${{ secrets.SHIFTLEFT_ORG_ID }} \
            --access-token ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }} \
            --api-token ${{ secrets.SHIFTLEFT_API_TOKEN }} \
            --type container \
            --app my-app \
            --team my-team \
            --force \
            --wait \
            $IMAGE_ID:$IMAGE_TAG
        env:
          SHIFTLEFT_ORG_ID: ${{ secrets.SHIFTLEFT_ORG_ID }}
          SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
          SHIFTLEFT_API_TOKEN: ${{ secrets.SHIFTLEFT_API_TOKEN }}

      - name: Upload ShiftLeft Scan Report
        uses: actions/upload-artifact@v3
        with:
          name: shiftleft-scan-report
          path: /path/to/report.sarif

      - name: Push Docker image if scan is successful
        if: success()
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}
          IMAGE_TAG=${{ github.sha }}
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          echo "Pushing Docker image with tag: $IMAGE_TAG"
          docker push $IMAGE_ID:$IMAGE_TAG
