name: Shiftleftcode Scan

on:
  workflow_call:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions: write-all

jobs:
  Scan-Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Perform Scan
      uses: ShiftLeftSecurity/scan-action@master
      env:
        WORKSPACE: ""
        GITHUB_TOKEN: ${{ secrets.BEASTSPY}}
        SCAN_AUTO_BUILD: true
      with:
        output: reports.sarif
    - name: Upload report
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: reports.sarif
