      - name: Set up ShiftLeft CLI
        run: |
          # Download and install ShiftLeft CLI
          curl -L -o /usr/local/bin/sl https://cdn.shiftleft.io/download/sl
          chmod a+rx /usr/local/bin/sl

      - name: Run ShiftLeft Scan
        id: scan
        uses: ShiftLeftSecurity/scan-action@master
        with:
          type: "credscan,java,depscan"
        env:
          SHIFTLEFT_ORG_ID: ${{ secrets.SHIFTLEFT_ORG_ID }}
          SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
          SHIFTLEFT_API_TOKEN: ${{ secrets.SHIFTLEFT_API_TOKEN }}

      - name: Upload SARIF Report
        if: success()  # Only runs if previous steps succeed
        uses: actions/upload-artifact@v3
        with:
          name: shiftleft-scan-report
          path: ./report.sarif
