name: ShiftLeft Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run ShiftLeft Scan
      run: |
        # Assuming you have ShiftLeft CLI installed and configured
        shiftleft scan --project your-project-name --format json --output /path/to/report.json

    - name: Upload Scan Report
      uses: actions/upload-artifact@v3
      with:
        name: shiftleft-scan-report
        path: /path/to/report.json
